#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_get dyfi/username
sed -i "s/^User.*/User $RET/" /etc/dyfi-update.conf

db_get dyfi/password
sed -i "s/^Password.*/Password $RET/" /etc/dyfi-update.conf

db_get dyfi/hosts
sed -i "s/^Hosts.*/Hosts $RET/" /etc/dyfi-update.conf

#DEBHELPER#
