#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_get dyfi/username
sed -i "s/^User.*/User $RET/" /etc/dyfi-update.conf

db_get dyfi/password
sed -i "s/^Password.*/Password $RET/" /etc/dyfi-update.conf

db_get dyfi/hosts
sed -i "s/^Hosts.*/Hosts $RET/" /etc/dyfi-update.conf

case "$1" in
  configure)
    if ! getent passwd dyfi > /dev/null; then
        adduser --quiet \
                --system \
                --group \
                --no-create-home \
                --home /nonexistent \
                --disabled-password \
                dyfi
    fi
    touch /var/log/dyfi-update.log
    chown dyfi:dyfi /usr/share/dyfi/dyfi-update.pl /var/log/dyfi-update.log /etc/dyfi-update.conf
  ;;
esac
#DEBHELPER#
