#!/bin/sh -e

. /usr/share/debconf/confmodule

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper disable dyfi.service >/dev/null
		deb-systemd-helper purge dyfi.service >/dev/null
		deb-systemd-helper unmask dyfi.service >/dev/null
	fi
fi

if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
